import { required, setAuthActionTokenProvider } from "./client-api.js";
import type { Config, Session } from "./client-types.js";

export const state: { session: Session | null; config: Config | null; streaming: boolean; aborting: boolean; controller: AbortController | null } = {
  session: null,
  config: null,
  streaming: false,
  aborting: false,
  controller: null,
};

// Privileged settings/auth mutations read their token from the loaded config.
setAuthActionTokenProvider(() => state.config?.authActionToken);

export const elements = {
  app: required<HTMLElement>("app"),
  terminal: required<HTMLElement>("terminal"),
  sessionList: required<HTMLElement>("session-list"),
  planningTaskList: required<HTMLElement>("planning-task-list"),
  activeAgentList: required<HTMLElement>("active-agent-list"),
  transcript: required<HTMLElement>("transcript"),
  emptyState: required<HTMLElement>("empty-state"),
  historyStatus: required<HTMLElement>("history-status"),
  composer: required<HTMLFormElement>("composer"),
  composerShell: required<HTMLElement>("composer-shell"),
  commandMenu: required<HTMLElement>("command-menu"),
  historySearch: required<HTMLElement>("history-search"),
  historyQuery: required<HTMLInputElement>("history-query"),
  historyResults: required<HTMLElement>("history-results"),
  prompt: required<HTMLTextAreaElement>("prompt"),
  attachments: required<HTMLElement>("attachments"),
  attachButton: required<HTMLButtonElement>("attach-button"),
  fileInput: required<HTMLInputElement>("file-input"),
  queue: required<HTMLButtonElement>("queue-button"),
  queuedMessage: required<HTMLElement>("queued-message"),
  queuedMessageContent: required<HTMLElement>("queued-message-content"),
  submit: required<HTMLButtonElement>("submit-button"),
  newSession: required<HTMLButtonElement>("new-session"),
  selectSession: required<HTMLButtonElement>("select-session"),
  toggleSidebar: required<HTMLButtonElement>("toggle-sidebar"),
  closeSidebar: required<HTMLButtonElement>("close-sidebar"),
  sessionTitle: required<HTMLElement>("session-title"),
  sessionDirectories: required<HTMLElement>("session-directories"),
  model: required<HTMLElement>("model-label"),
  modelSelector: required<HTMLButtonElement>("model-selector"),
  thinkingLevel: required<HTMLElement>("thinking-level-label"),
  thinkingLevelButton: required<HTMLButtonElement>("thinking-level-button"),
  providerDot: required<HTMLElement>("provider-dot"),
  modeBanner: required<HTMLElement>("mode-banner"),
  modePlan: required<HTMLInputElement>("mode-plan"),
  modeNormal: required<HTMLInputElement>("mode-normal"),
  contextMeter: required<HTMLElement>("context-meter"),
  contextMeterBar: required<HTMLElement>("context-meter-bar"),
  contextMeterValue: required<HTMLElement>("context-meter-value"),
  landingDialog: required<HTMLElement>("landing-dialog"),
  landingNewSession: required<HTMLButtonElement>("landing-new-session"),
  landingSelectSession: required<HTMLButtonElement>("landing-select-session"),
  newSessionDialog: required<HTMLElement>("new-session-dialog"),
  newSessionForm: required<HTMLFormElement>("new-session-form"),
  newSessionClose: required<HTMLButtonElement>("new-session-close"),
  newSessionName: required<HTMLInputElement>("new-session-name"),
  newSessionPath: required<HTMLInputElement>("new-session-path"),
  newSessionCompletions: required<HTMLElement>("new-session-completions"),
  newSessionSubmit: required<HTMLButtonElement>("new-session-submit"),
  sessionDialog: required<HTMLElement>("session-dialog"),
  sessionDialogClose: required<HTMLButtonElement>("session-dialog-close"),
  sessionSearch: required<HTMLInputElement>("session-search"),
  modelDialog: required<HTMLElement>("model-dialog"),
  modelDialogClose: required<HTMLButtonElement>("model-dialog-close"),
  modelSearch: required<HTMLInputElement>("model-search"),
  modelList: required<HTMLElement>("model-list"),
  settingsButton: required<HTMLButtonElement>("settings-button"),
  settingsDialog: required<HTMLElement>("settings-dialog"),
  settingsClose: required<HTMLButtonElement>("settings-close"),
  settingsForm: required<HTMLElement>("settings-form"),
  settingsThemeOptions: required<HTMLElement>("settings-theme-options"),
  settingsDefaults: required<HTMLElement>("settings-defaults"),
  settingsAddProvider: required<HTMLButtonElement>("settings-add-provider"),
  settingsLoginCodex: required<HTMLButtonElement>("settings-login-codex"),
  settingsProviderList: required<HTMLElement>("settings-provider-list"),
  settingsAddAgent: required<HTMLButtonElement>("settings-add-agent"),
  settingsAgentList: required<HTMLElement>("settings-agent-list"),
  settingsPath: required<HTMLElement>("settings-path"),
  settingsError: required<HTMLElement>("settings-error"),
  settingsStatus: required<HTMLElement>("settings-status"),
  settingsCancel: required<HTMLButtonElement>("settings-cancel"),
  settingsSave: required<HTMLButtonElement>("settings-save"),
  settingsSaveClose: required<HTMLButtonElement>("settings-save-close"),
  tasksDialog: required<HTMLElement>("tasks-dialog"),
  tasksDialogTitle: required<HTMLElement>("tasks-dialog-title"),
  tasksDialogBody: required<HTMLElement>("tasks-dialog-body"),
  tasksDialogHints: required<HTMLElement>("tasks-dialog-hints"),
  tasksBack: required<HTMLButtonElement>("tasks-back"),
  tasksClose: required<HTMLButtonElement>("tasks-close"),
  tasksStop: required<HTMLButtonElement>("tasks-stop"),
  gitDialog: required<HTMLElement>("git-dialog"),
  gitDialogTitle: required<HTMLElement>("git-dialog-title"),
  gitDialogBody: required<HTMLElement>("git-dialog-body"),
  gitDialogHints: required<HTMLElement>("git-dialog-hints"),
  gitClose: required<HTMLButtonElement>("git-close"),
  gitCommit: required<HTMLButtonElement>("git-commit"),
  gitCommitPush: required<HTMLButtonElement>("git-commit-push"),
  questionDialog: required<HTMLElement>("question-dialog"),
  questionDialogTitle: required<HTMLElement>("question-dialog-title"),
  questionDialogBody: required<HTMLElement>("question-dialog-body"),
  questionDialogHints: required<HTMLElement>("question-dialog-hints"),
  questionClose: required<HTMLButtonElement>("question-close"),
  questionSubmit: required<HTMLButtonElement>("question-submit"),
  planModeDialog: required<HTMLElement>("plan-mode-dialog"),
  planModeDialogTitle: required<HTMLElement>("plan-mode-dialog-title"),
  planModeDialogBody: required<HTMLElement>("plan-mode-dialog-body"),
  planModeDialogHints: required<HTMLElement>("plan-mode-dialog-hints"),
  planModeClose: required<HTMLButtonElement>("plan-mode-close"),
  planModeDecline: required<HTMLButtonElement>("plan-mode-decline"),
  planModeApprove: required<HTMLButtonElement>("plan-mode-approve"),
  planModeNewSession: required<HTMLButtonElement>("plan-mode-new-session"),
  toast: required<HTMLElement>("toast"),
};
